package com.mastery.generics;

import com.mastery.annotations.Difficulty;
import com.mastery.annotations.JavaConcept;
import com.mastery.annotations.JavaConcept.Question;
import com.mastery.utils.ConsoleFormatter;

import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;

@JavaConcept(
    name = "Type Erasure and Runtime Bypasses",
    difficulty = Difficulty.EXPERT,
    what = "Java Generics are implemented via Type Erasure. The compiler enforces type checks at compile-time and erases generic type parameters to their bounds (or Object) in the generated bytecode, inserting implicit casts where needed.",
    whyItMatters = "Because generics are erased, generic type parameters are not available at runtime. Reflection can bypass generic type checks, inserting mismatched types directly into collections and causing ClassCastExceptions during reads.",
    keyPoints = {
        "Type parameters are replaced with their first bound (or Object if unbounded) in class bytecode.",
        "Overloading methods with same raw signature but different generics (e.g. print(List<String>) vs print(List<Integer>)) causes compile errors.",
        "Using reflection, you can add any type to a parameterized list because JVM bytecode only sees raw lists."
    },
    interviewQuestions = {
        @Question(
            question = "Why does Java use Type Erasure instead of preserving generic types at runtime?",
            answer = "Java introduced generics in Java 5. To maintain backward compatibility with old libraries that used raw collections (pre-Java 5), designers chose type erasure so that raw collections and generic collections compile to the exact same bytecode."
        ),
        @Question(
            question = "How can you bypass generic compile safety check to insert a String into a List<Integer>?",
            answer = "By using reflection. You can fetch the list's 'add' method from class metadata and invoke it at runtime, which bypasses compiler type checking."
        )
    },
    pitfalls = {
        "Using instanceof checks with generic parameters (e.g. list instanceof List<String> is forbidden due to type erasure).",
        "Runtime ClassCastException when reading objects from a list that has been corrupted by reflection or raw type operations."
    }
)
public class TypeErasure {
    public static void main(String[] args) {
        ConsoleFormatter.printHeader("Type Erasure & Runtime Bypasses");

        // 1. Same runtime Class identity
        ConsoleFormatter.printStep("Class Identity Check", "Validating that generic classes resolve to the same Class object");
        List<Integer> intList = new ArrayList<>();
        List<String> stringList = new ArrayList<>();

        System.out.println("intList class: " + intList.getClass().getName());
        System.out.println("stringList class: " + stringList.getClass().getName());
        System.out.println("intList.getClass() == stringList.getClass(): " + (intList.getClass() == stringList.getClass()));

        if (intList.getClass() == stringList.getClass()) {
            ConsoleFormatter.printSuccess("Runtime Class objects are identical (ArrayList). Generics erased.");
        }

        // 2. Bypassing Type Safety with Reflection
        ConsoleFormatter.printStep("Reflection Bypassing", "Inserting a String into a List<Integer> using reflection");
        List<Integer> numbers = new ArrayList<>();
        numbers.add(10);
        numbers.add(20);

        try {
            // Bypass compile-time safety check
            Method addMethod = numbers.getClass().getMethod("add", Object.class);
            addMethod.invoke(numbers, "Sneaky String inserted via Reflection!"); // Bypasses generic check!
            
            ConsoleFormatter.printSuccess("String inserted into List<Integer> successfully without runtime exception.");
            System.out.println("Numbers contents: " + numbers); // Prints [10, 20, Sneaky String...]

            // 3. The Runtime Trap
            ConsoleFormatter.printStep("ClassCastException Trap", "Attempting to read the corrupted list using type-safe checks");
            
            // This loop compiles fine because compiler assumes everything is Integer.
            // When iterating, compiler inserts an implicit cast: (Integer) item
            for (Integer num : numbers) {
                System.out.println("Read value: " + num);
            }
        } catch (ClassCastException cce) {
            ConsoleFormatter.printError("ClassCastException caught during type-safe iteration of corrupted list!", cce);
        } catch (Exception e) {
            ConsoleFormatter.printError("Unexpected reflection error: " + e.getMessage(), e);
        }
    }
}
